name: Build demos

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  repository_dispatch:
    types: [ build ]
  schedule:
    - cron: '0 0 * * 1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ApiDemos:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install NDK
      run: |
        sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"

    - name: Build and check
      run: |
        cd ApiDemos
        for dir in ./*/ ; do ( cd "$dir" && ./gradlew assemble lint ); done

  build-WearOS:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build and check
      run: cd WearOS && ./gradlew assembleDebug lintDebug

  build-tutorials:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build and check
      run: |
        cd tutorials
        for dir in ./*/
        do
          cd "$dir"
          for tutorial in ./*/
          do
            cd "$tutorial" && ./gradlew assembleDebug lintDebug
            cd ..
          done
          cd ..
        done
